### PR TITLE
Social media website - Milestone: friendships v2

### PR DESCRIPTION
**Pull request by mahmoud717**
in this milestone, I implemented  two-row friendships

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required 🔴 

Hello,

Thank you for the well-done job
However, there are some issues

1- Your `rubocop.yml` file is different than the required one. Kindly follow this [link](https://github.com/microverseinc/linters-config/tree/master/ror) to set up the good one

2- Running `rubocop` in your project return many offenses
```rb
28 files inspected, 19 offenses detected
```

3- There is logic in some views. Kindly move it in view helpers
https://github.com/mahmoud717/rilas-social/blob/659c0cb32dab6323b6b04d54948e97936ac978fa/app/views/users/friends.html.erb#L3-L7
https://github.com/mahmoud717/rilas-social/blob/659c0cb32dab6323b6b04d54948e97936ac978fa/app/views/posts/_post.html.erb#L1
To avoid this latter, you can update your code with this
```
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
Add it in your `User` model and in the post controller
```rb
def timeline_posts
    @timeline_posts ||= current_user.friends_and_own_posts
  end
```

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required 🔴 

Hello,

Thank you for implementing the suggested changes
However, there are still some issues

1-  Your rubocop.yml file is different than the required one. Kindly follow this [link](https://github.com/microverseinc/linters-config/tree/master/ror) to set up the good one

2- There is still that logic in a view
https://github.com/mahmoud717/rilas-social/blob/b4f552d41a3b7140528cb08fd4e303599fdc9a42/app/views/users/_user.html.erb#L1

3- The timeline posts must be ordered in desc, the most recent on top, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png), 

This timeline post
Screenshot at 2020-11-05 10:01:09

 is different from this database content
```SQL
ror_social_scaffold_development=# select * from posts;
 id | user_id |          content          |         created_at         |         updated_at         
----+---------+---------------------------+----------------------------+----------------------------
  1 |       1 | Alice is there. And  you? | 2020-11-05 08:54:40.661652 | 2020-11-05 08:54:40.661652
  2 |       2 | Bob, yes it's me!         | 2020-11-05 08:54:56.802212 | 2020-11-05 08:54:56.802212
(2 rows)

```
Bob's post must come first.
Kindly fix that.

Once changes are done, kindly submit a new code review request
Thanks

Mael FOSSO

**Comment by mahmoud717** [comment]
- can you please check the .rubocop.yml file before saying that it needs change

**Review by rOluochKe — APPROVED** [review]
Hello @mahmoud717 
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
